services:
  open-webui:
    build:
      context: .
      dockerfile: Dockerfile
    image: openwebui:latest
    container_name: open-webui
    #ports:
      #- "127.0.0.1:8080:8080"
    network_mode: host

    volumes:
      - open-webui:/app/backend/data
    env_file:
      - .env
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  open-webui: {}

